version: "2"

services:

  web:
    image: silintl/ssp-base:develop
    ports:
      - "80:80"
    volumes:
      - ./:/silauth
      - ./development/run-debug.sh:/data/run.sh
      - ./auth.json:/root/.composer/auth.json
      - ./development/enable-debug.sh:/data/enable-debug.sh
      - ./development/run-dev.sh:/data/run-dev.sh
      - ./development/run-tests.sh:/data/run-tests.sh
      - ./development/symlink.sh:/data/symlink.sh
      - ./src:/data/src
    env_file:
      - ./common.env
      - ./local.env
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: silauth
      MYSQL_USER: silauth
      MYSQL_PASSWORD: silauth
    depends_on:
      - db
    command: ["/data/run-dev.sh"]

  tests:
    image: silintl/ssp-base:develop
    volumes_from:
      - web
    volumes:
      - ./composer.json:/data/composer.json
      - ./composer.lock:/data/composer.lock
      - ./development/run-tests.sh:/data/run-tests.sh
      - ./features:/data/features
      - ./vendor:/data/vendor
      - ${COMPOSER_CACHE_DIR}:/composer
    env_file:
      - ./common.env
      - ./local.env
    environment:
      COMPOSER_CACHE_DIR: /composer
      MYSQL_HOST: testdb
      MYSQL_DATABASE: test
      MYSQL_USER: silauth
      MYSQL_PASSWORD: silauth
      IDP_DOMAIN_NAME: fake.example.com
    depends_on:
      - testdb
    working_dir: /data
    command: ["/data/run-tests.sh"]

  db:
    image: silintl/mariadb:latest
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: r00tp@ss!
      MYSQL_DATABASE: silauth
      MYSQL_USER: silauth
      MYSQL_PASSWORD: silauth

  testdb:
    image: silintl/mariadb:latest
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: r00tp@ss!
      MYSQL_DATABASE: test
      MYSQL_USER: silauth
      MYSQL_PASSWORD: silauth

  dbadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: silauth
      PMA_PASSWORD: silauth

